// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsWjyel3GC5nJfbivFj1ul_iYyjpADl8',
    appId: '1:953968862880:web:b1b7824345846933aa4bc5',
    messagingSenderId: '953968862880',
    projectId: 'flutter-5fde7',
    authDomain: 'flutter-5fde7.firebaseapp.com',
    storageBucket: 'flutter-5fde7.appspot.com',
    measurementId: 'G-1MFDLVXR1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZ1ugav3U3BR7YJgJgZUXI8AVMM1wc_4',
    appId: '1:953968862880:android:e5e016b95b32d361aa4bc5',
    messagingSenderId: '953968862880',
    projectId: 'flutter-5fde7',
    storageBucket: 'flutter-5fde7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybbeH2mE4wecXDGkf2uGTuao0E9Ebr44',
    appId: '1:953968862880:ios:bc43d540aeaa96edaa4bc5',
    messagingSenderId: '953968862880',
    projectId: 'flutter-5fde7',
    storageBucket: 'flutter-5fde7.appspot.com',
    iosBundleId: 'com.example.flutterCiCdBitrise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAybbeH2mE4wecXDGkf2uGTuao0E9Ebr44',
    appId: '1:953968862880:ios:bc43d540aeaa96edaa4bc5',
    messagingSenderId: '953968862880',
    projectId: 'flutter-5fde7',
    storageBucket: 'flutter-5fde7.appspot.com',
    iosBundleId: 'com.example.flutterCiCdBitrise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrsWjyel3GC5nJfbivFj1ul_iYyjpADl8',
    appId: '1:953968862880:web:59074fc7c6932877aa4bc5',
    messagingSenderId: '953968862880',
    projectId: 'flutter-5fde7',
    authDomain: 'flutter-5fde7.firebaseapp.com',
    storageBucket: 'flutter-5fde7.appspot.com',
    measurementId: 'G-9LL48527ZK',
  );
}
